### ISSUE TITLE
Outdated clean-css strips away flexbox properties

### ISSUE THREAD

**Issue by lunaleaps** [jairajs89/zerver#25]
Running 0.15.x version of zerver, using clean-css 2.1.6 and running into an issue where flexbox properties are affected by minifying the css via clean-css.

Similar issues are documented in clean-css for versions < 2.4 with a fix here:
https://github.com/jakubpawlowicz/clean-css/issues/290

There is an option to add `--skip-aggresive-merging` flag to clean-css but wondering if we can update the version to the latest version 3.4 that has solved the issue and no longer requires the `skip-aggressive-merging` flag

**Comment by jairajs89** [comment]
fixed in v0.17.6
